# -*- coding: utf-8 -*-
"""python Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ls1gArJGiIDRWrptyM7UpJYB41KUu4o6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Orders list from assessment
orders = [1200, 3400, 560, 8900, 2300, 1200, 3400]

print("Original orders:", orders)
print()

#  Convert to Pandas Series (NumPy under the hood)
orders_series = pd.Series(orders)
print(" - Pandas Series:")
print(orders_series)
print()

#  Remove duplicates using Pandas drop_duplicates()
unique_orders = orders_series.drop_duplicates()
print(" - After removing duplicates:")
print(unique_orders)
print()

#  Sort descending using Pandas sort_values()
sorted_orders = unique_orders.sort_values(ascending=False)
print(" - Sorted descending:")
print(sorted_orders)
print()

# Get top 3 highest values using Pandas head(3)
top_3_orders = sorted_orders.head(3)
print(" TOP 3 HIGHEST ORDERS:")
print(top_3_orders)
print(f"Top 3 values: {top_3_orders.tolist()}")

print(f"Top 3 values: {top_3_orders.tolist()}")


plt.figure(figsize=(12,4))

# Chart 1: TOP 3 Bar Chart
plt.subplot(1,2,1)
ranks = ['1st', '2nd', '3rd']
values = top_3_orders.values
plt.barh(ranks, values, color=['gold','silver','orange'])
plt.title('🏆 Top 3 Orders')
for i, v in enumerate(values):
    plt.text(v+100, i, f'₹{v:,.0f}')

# Q2: IQR Outlier Detection Function
def detect_outliers_iqr(data):
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[(data < lower_bound) | (data > upper_bound)]
    return outliers, lower_bound, upper_bound

# Apply to your orders data
outliers, lb, ub = detect_outliers_iqr(orders_series)
print(f"IQR Bounds: ₹{lb:.0f} - ₹{ub:.0f}")
print(f"Outliers: {outliers.tolist()}")

plt.figure(figsize=(10,4))

# Chart 1: Box plot with outliers marked
plt.subplot(1,2,1)
sns.boxplot(y=orders_series, color='lightblue')
plt.axhspan(lb, ub, alpha=0.2, color='green', label=f'Normal Range (₹{lb:.0f}-₹{ub:.0f})')
plt.axhline(lb, color='orange', linestyle='--', label='Lower Bound')
plt.axhline(ub, color='orange', linestyle='--', label='Upper Bound')
plt.title('IQR Outlier Detection')
plt.legend()

# Chart 2: Outliers highlighted
plt.subplot(1,2,2)
colors = ['red' if x in outliers.values else 'blue' for x in orders_series]
sns.barplot(y=orders_series.values, x=range(len(orders_series)), palette=colors)
plt.title('Orders (Red = Outliers)')

plt.tight_layout()
plt.show()